[package]
name = "sub_application"
version = "0.1.0"
edition = "2021"

[dependencies]
google-cloud-pubsub = "0.30.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.7.13"
google-cloud-gax = "0.19.2"
google-cloud-googleapis = "0.16.0"
